TRANSACT_WRITE_LIMIT = 100
BATCH_WRITE_LIMIT = 25

MAX_ISSUE_ID_LEN = 16
MIN_ISSUE_ID_LEN = 3
RETRY_ISSUE_ID_COLLISIONS = 5

# Full-jitter exponential backoff for TransactionConflict retries
TRANSACT_RETRY_ATTEMPTS = 5
TRANSACT_RETRY_BASE_DELAY = 0.05
TRANSACT_RETRY_MAX_DELAY = 1.0
